services:
  api:
    class: Photomover\Service\Api
    arguments:
      - %user_id%
      - %access_token%
      - %api_ver%
      - %api_rps_limit%
  authorizer:
    class: Photomover\Service\Authorizer
    arguments:
      - %client_id%
      - %client_secret%
      - %api_ver%
      - %vk_login%
      - %vk_pass%
